name: Build and Deploy APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ccache libncurses5-dev libstdc++6 zlib1g
        python -m pip install --upgrade pip
        pip install buildozer cython

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Setup Android NDK
      run: |
        echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;25.2.9519653" --sdk_root=${ANDROID_SDK_ROOT}
        echo "ANDROID_NDK_HOME=${ANDROID_SDK_ROOT}/ndk/25.2.9519653" >> $GITHUB_ENV

    - name: Build APK
      run: |
        buildozer android debug
      env:
        ANDROID_NDK_HOME: ${{ env.ANDROID_NDK_HOME }}

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: bin/*.apk
