name: Build and Deploy APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ccache libncurses5-dev libstdc++6 zlib1g
        python -m pip install --upgrade pip
        pip install buildozer cython

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 30
        ndk-version: 25.2.9519653
        cmake-version: 3.10.2.4988404

    - name: Cache Buildozer dependencies
      uses: actions/cache@v2
      with:
        path: ~/.buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}

    - name: Build APK
      run: |
        buildozer android debug -v
      env:
        ANDROID_NDK_HOME: ${{ env.ANDROID_NDK_HOME }}
      timeout-minutes: 45

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: bin/*.apk
      if: success()

    - name: Upload build logs on failure
      uses: actions/upload-artifact@v3
      with:
        name: buildozer-logs
        path: .buildozer/logs
      if: failure()
